apiVersion: v1
kind: Namespace
metadata:
  name: cyberdock
  labels:
    name: cyberdock
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    monitoring.service: cyberdock
    app: cyberdock
  name: cyberdock
  namespace: cyberdock
spec:
  replicas: 1
  selector:
    matchLabels:
      monitoring.service: cyberdock
  strategy:
    type: Recreate
  template:
    metadata:
      annotations: {}
      labels:
        monitoring.service: cyberdock
        app: cyberdock
        lbtype: external
    spec:
      containers:
      - name: cyberdock
        image: ghcr.io/ramborogers/cyberdock:latest
        imagePullPolicy: Always
        env:
        - name: TZ
          value: America/New_York
        ports:
        - containerPort: 5000
          name: http-cyberdock
          protocol: TCP
        volumeMounts:
        - mountPath: /cyberdock/data
          name: cyberdock-data
        resources: {}
      volumes:
      - name: cyberdock-data
        persistentVolumeClaim:
          claimName: cyberdock-data
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    monitoring.service: cyberdock
  name: cyberdock
  namespace: cyberdock
spec:
  type: LoadBalancer
  ports:
  - name: "https-cyberdock"
    port: 443
    targetPort: 5000
    protocol: TCP
  selector:
    app: cyberdock
  # If you want to specify a specific IP from your MetalLB IP pool, uncomment the line below
  # loadBalancerIP: 192.168.1.240
status:
  loadBalancer: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    monitoring.service: cyberdock-data
  name: cyberdock-data
  namespace: cyberdock
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Pi
status: {}


